kind: pipeline
type: docker
name: default

steps:
  - name: build_and_publish
    image: plugins/docker:linux-amd64
    settings:
      password:
        from_secret: docker_password
      registry: docker.asperti.com
      repo: docker.asperti.com/paspo/hassio-ot-recorder
      tags:
        - latest
        - 0.2.2
      username:
        from_secret: docker_username

trigger:
  event:
    - tag
    - push
