FREEBSD ?= no
INSTALLDIR = /usr
WITH_MQTT ?= yes
WITH_HTTP ?= yes
WITH_LUA ?= no
WITH_PING ?= yes
WITH_KILL ?= no
WITH_ENCRYPT ?= yes
WITH_GREENWICH ?= no
STORAGEDEFAULT = /share/ot-recorder/
DOCROOT = /var/spool/owntracks/recorder/htdocs
GHASHPREC = 7
JSON_INDENT ?= no
CONFIGFILE = /etc/ot-recorder.cfg
MOSQUITTO_INC = -I/usr/include
MOSQUITTO_LIB = -L/usr/lib
MORELIBS += # -lssl
LUA_CFLAGS = `pkg-config --cflags lua`
LUA_LIBS   = `pkg-config --libs lua`
SODIUM_CFLAGS = `pkg-config --cflags libsodium`
SODIUM_LIBS   = `pkg-config --libs libsodium`
GEOCODE_TIMEOUT = 4000

